export type ThemePreset = {
  value: string;
  label: string;
  description: string;
  config: Record<string, string>;
};

export const THEME_PRESETS: ThemePreset[] = [
  {
    value: 'boutique',
    label: 'Boutique Glow',
    description: 'Warm luxury tones for fashion and premium stores.',
    config: {
      theme: 'boutique',
      fontFamily: 'Playfair Display',
      primaryColor: '#d97706',
      backgroundColor: '#fffaf2',
      heroBgColor: '#1f1720',
      aboutBgColor: '#fffaf2',
      productsBgColor: '#fff6e8',
      headingColor: '#2b1608',
      textColor: '#6b4d35',
      heroHeadingColor: '#fff7ed',
      heroTextColor: '#f3e8d8',
      aboutHeadingColor: '#2b1608',
      aboutTextColor: '#6b4d35',
      productsHeadingColor: '#2b1608',
      productsTextColor: '#6b4d35',
      navBgColor: '#fffaf2',
      navTextColor: '#6b4d35',
      footerBgColor: '#1f1720',
      footerHeadingColor: '#fff7ed',
      footerTextColor: '#d6c0a6',
      navFontFamily: 'Playfair Display',
      heroFontFamily: 'Playfair Display',
      aboutFontFamily: 'Lora',
      productsFontFamily: 'Lora',
      footerFontFamily: 'Lora',
      animationStyle: 'reveal',
      navAnimationStyle: 'reveal',
      heroAnimationStyle: 'reveal',
    },
  },
  {
    value: 'street',
    label: 'Street Signal',
    description: 'Bold contrast for sneakers, drops, and youth brands.',
    config: {
      theme: 'street',
      fontFamily: 'Montserrat',
      primaryColor: '#ef4444',
      backgroundColor: '#0b0b0f',
      heroBgColor: '#111827',
      aboutBgColor: '#111827',
      productsBgColor: '#18181b',
      headingColor: '#f9fafb',
      textColor: '#d4d4d8',
      heroHeadingColor: '#ffffff',
      heroTextColor: '#e4e4e7',
      aboutHeadingColor: '#fafafa',
      aboutTextColor: '#d4d4d8',
      productsHeadingColor: '#fafafa',
      productsTextColor: '#d4d4d8',
      navBgColor: '#09090b',
      navTextColor: '#f4f4f5',
      footerBgColor: '#09090b',
      footerHeadingColor: '#ffffff',
      footerTextColor: '#a1a1aa',
      navFontFamily: 'Montserrat',
      heroFontFamily: 'Montserrat',
      aboutFontFamily: 'Outfit',
      productsFontFamily: 'Outfit',
      footerFontFamily: 'Outfit',
      animationStyle: 'slide-up',
      navAnimationStyle: 'fade-in',
      heroAnimationStyle: 'zoom-out',
    },
  },
  {
    value: 'minimal',
    label: 'Minimal Muse',
    description: 'Calm neutrals and airy spacing for curated shops.',
    config: {
      theme: 'minimal',
      fontFamily: 'Outfit',
      primaryColor: '#0f766e',
      backgroundColor: '#f8fafc',
      heroBgColor: '#e2e8f0',
      aboutBgColor: '#ffffff',
      productsBgColor: '#f1f5f9',
      headingColor: '#0f172a',
      textColor: '#475569',
      heroHeadingColor: '#0f172a',
      heroTextColor: '#334155',
      aboutHeadingColor: '#0f172a',
      aboutTextColor: '#475569',
      productsHeadingColor: '#0f172a',
      productsTextColor: '#475569',
      navBgColor: '#ffffff',
      navTextColor: '#334155',
      footerBgColor: '#0f172a',
      footerHeadingColor: '#f8fafc',
      footerTextColor: '#cbd5e1',
      navFontFamily: 'Outfit',
      heroFontFamily: 'Outfit',
      aboutFontFamily: 'Inter',
      productsFontFamily: 'Inter',
      footerFontFamily: 'Inter',
      animationStyle: 'fade-in',
      navAnimationStyle: 'fade-in',
      heroAnimationStyle: 'blur-in',
    },
  },
  {
    value: 'earth',
    label: 'Earth Market',
    description: 'Organic greens for handmade, local, and eco brands.',
    config: {
      theme: 'earth',
      fontFamily: 'Lora',
      primaryColor: '#65a30d',
      backgroundColor: '#f7f7ed',
      heroBgColor: '#365314',
      aboutBgColor: '#fefce8',
      productsBgColor: '#ecfccb',
      headingColor: '#365314',
      textColor: '#4d5c37',
      heroHeadingColor: '#fefce8',
      heroTextColor: '#e7f3c8',
      aboutHeadingColor: '#365314',
      aboutTextColor: '#4d5c37',
      productsHeadingColor: '#365314',
      productsTextColor: '#4d5c37',
      navBgColor: '#fefce8',
      navTextColor: '#4d5c37',
      footerBgColor: '#365314',
      footerHeadingColor: '#fefce8',
      footerTextColor: '#d9f99d',
      navFontFamily: 'Lora',
      heroFontFamily: 'Lora',
      aboutFontFamily: 'Lora',
      productsFontFamily: 'Lora',
      footerFontFamily: 'Lora',
      animationStyle: 'reveal',
      navAnimationStyle: 'fade-in',
      heroAnimationStyle: 'scale-in',
    },
  },
  {
    value: 'royal',
    label: 'Royal Velvet',
    description: 'Deep jewel colors for elevated and formal brands.',
    config: {
      theme: 'royal',
      fontFamily: 'Cinzel',
      primaryColor: '#c084fc',
      backgroundColor: '#140f1f',
      heroBgColor: '#24143d',
      aboutBgColor: '#1a1329',
      productsBgColor: '#251b38',
      headingColor: '#f5e9ff',
      textColor: '#d8c7f1',
      heroHeadingColor: '#ffffff',
      heroTextColor: '#e9d5ff',
      aboutHeadingColor: '#f5e9ff',
      aboutTextColor: '#d8c7f1',
      productsHeadingColor: '#f5e9ff',
      productsTextColor: '#d8c7f1',
      navBgColor: '#140f1f',
      navTextColor: '#f5e9ff',
      footerBgColor: '#0f0a18',
      footerHeadingColor: '#ffffff',
      footerTextColor: '#c4b5fd',
      navFontFamily: 'Cinzel',
      heroFontFamily: 'Cinzel',
      aboutFontFamily: 'Merriweather',
      productsFontFamily: 'Merriweather',
      footerFontFamily: 'Merriweather',
      animationStyle: 'flip-in',
      navAnimationStyle: 'fade-in',
      heroAnimationStyle: 'zoom-out',
    },
  },
  {
    value: 'coastal',
    label: 'Coastal Air',
    description: 'Bright seaside palette for resort and lifestyle stores.',
    config: {
      theme: 'coastal',
      fontFamily: 'Poppins',
      primaryColor: '#0ea5e9',
      backgroundColor: '#f0f9ff',
      heroBgColor: '#0f766e',
      aboutBgColor: '#ecfeff',
      productsBgColor: '#e0f2fe',
      headingColor: '#164e63',
      textColor: '#155e75',
      heroHeadingColor: '#ecfeff',
      heroTextColor: '#cffafe',
      aboutHeadingColor: '#164e63',
      aboutTextColor: '#155e75',
      productsHeadingColor: '#164e63',
      productsTextColor: '#155e75',
      navBgColor: '#ecfeff',
      navTextColor: '#155e75',
      footerBgColor: '#164e63',
      footerHeadingColor: '#ecfeff',
      footerTextColor: '#bae6fd',
      navFontFamily: 'Poppins',
      heroFontFamily: 'Poppins',
      aboutFontFamily: 'Poppins',
      productsFontFamily: 'Poppins',
      footerFontFamily: 'Poppins',
      animationStyle: 'fade-in',
      navAnimationStyle: 'slide-up',
      heroAnimationStyle: 'blur-in',
    },
  },
  {
    value: 'atelier',
    label: 'Atelier Rose',
    description: 'Soft editorial style for beauty and handmade sellers.',
    config: {
      theme: 'atelier',
      fontFamily: 'Cormorant Garamond',
      primaryColor: '#e11d48',
      backgroundColor: '#fff1f2',
      heroBgColor: '#4c0519',
      aboutBgColor: '#fff1f2',
      productsBgColor: '#ffe4e6',
      headingColor: '#4c0519',
      textColor: '#881337',
      heroHeadingColor: '#fff1f2',
      heroTextColor: '#fecdd3',
      aboutHeadingColor: '#4c0519',
      aboutTextColor: '#881337',
      productsHeadingColor: '#4c0519',
      productsTextColor: '#881337',
      navBgColor: '#fff1f2',
      navTextColor: '#881337',
      footerBgColor: '#4c0519',
      footerHeadingColor: '#fff1f2',
      footerTextColor: '#fecdd3',
      navFontFamily: 'Cormorant Garamond',
      heroFontFamily: 'Cormorant Garamond',
      aboutFontFamily: 'Lora',
      productsFontFamily: 'Lora',
      footerFontFamily: 'Lora',
      animationStyle: 'scale-in',
      navAnimationStyle: 'fade-in',
      heroAnimationStyle: 'reveal',
    },
  },
  {
    value: 'tech',
    label: 'Tech Pulse',
    description: 'Sharp neon edge for gadgets and modern catalog stores.',
    config: {
      theme: 'tech',
      fontFamily: 'JetBrains Mono',
      primaryColor: '#22c55e',
      backgroundColor: '#020617',
      heroBgColor: '#020617',
      aboutBgColor: '#0f172a',
      productsBgColor: '#111827',
      headingColor: '#e2e8f0',
      textColor: '#94a3b8',
      heroHeadingColor: '#f8fafc',
      heroTextColor: '#cbd5e1',
      aboutHeadingColor: '#e2e8f0',
      aboutTextColor: '#94a3b8',
      productsHeadingColor: '#e2e8f0',
      productsTextColor: '#94a3b8',
      navBgColor: '#020617',
      navTextColor: '#e2e8f0',
      footerBgColor: '#020617',
      footerHeadingColor: '#f8fafc',
      footerTextColor: '#94a3b8',
      navFontFamily: 'JetBrains Mono',
      heroFontFamily: 'JetBrains Mono',
      aboutFontFamily: 'JetBrains Mono',
      productsFontFamily: 'JetBrains Mono',
      footerFontFamily: 'JetBrains Mono',
      animationStyle: 'skew-in',
      navAnimationStyle: 'fade-in',
      heroAnimationStyle: 'flip-in',
    },
  },
  {
    value: 'sunset',
    label: 'Sunset Bazaar',
    description: 'Color-rich gradient mood for vibrant catalog shops.',
    config: {
      theme: 'sunset',
      fontFamily: 'Merriweather',
      primaryColor: '#f97316',
      backgroundColor: '#fff7ed',
      heroBgColor: '#7c2d12',
      aboutBgColor: '#fffbeb',
      productsBgColor: '#ffedd5',
      headingColor: '#7c2d12',
      textColor: '#9a3412',
      heroHeadingColor: '#fff7ed',
      heroTextColor: '#fed7aa',
      aboutHeadingColor: '#7c2d12',
      aboutTextColor: '#9a3412',
      productsHeadingColor: '#7c2d12',
      productsTextColor: '#9a3412',
      navBgColor: '#fff7ed',
      navTextColor: '#9a3412',
      footerBgColor: '#7c2d12',
      footerHeadingColor: '#fff7ed',
      footerTextColor: '#fdba74',
      navFontFamily: 'Merriweather',
      heroFontFamily: 'Merriweather',
      aboutFontFamily: 'Merriweather',
      productsFontFamily: 'Merriweather',
      footerFontFamily: 'Merriweather',
      animationStyle: 'bounce-in',
      navAnimationStyle: 'slide-up',
      heroAnimationStyle: 'zoom-out',
    },
  },
];

export function getThemePreset(value?: string) {
  return THEME_PRESETS.find((preset) => preset.value === value) ?? THEME_PRESETS[0];
}
